let a=["Nabin","Anil","Aryan","Aman","Keshav","Pankaj"];
console.log(a);
console.log(a[0]);
console.log(a.length);
a.push("Nayan");
console.log(a[6]);
console.log(a.length);
a.sort();
console.log(a);
a.shift();
console.log(a);
a.unshift("Aman");
console.log(a);

let b=["Bhat","Giri","Dhami","Bhatta"];
console.log(b.reverse());
console.log(b);
b.pop();
console.log(b.pop());
console.log(b);
